import { z } from 'zod';
import '../../../shared/http/openapi';
import { AttachmentIds, AttachmentResponse } from '../../file';
import { UserReference } from '../../identity';

const Name = z.string().trim().min(1).max(100);
const Description = z.string().trim().max(500).nullable();
const MessageContent = z.string().trim().min(1).max(4000);
const ConversationTypeEnum = z.enum(['DIRECT', 'GROUP', 'CHANNEL']);
const ConversationRoleEnum = z.enum(['OWNER', 'ADMIN', 'MEMBER']);

// ─── Params & queries ──────────────────────────────────────────────────────

export const ConversationParams = z.object({ id: z.uuid() });
export const MessageParams = ConversationParams.extend({ messageId: z.uuid() });
export const ConversationMemberParams = ConversationParams.extend({ userId: z.uuid() });

export const ConversationListQuery = z.object({
  limit: z.coerce.number().int().min(1).max(100).default(30),
  cursor: z.string().min(1).max(512).optional(),
});

export const HistoryQuery = z
  .object({
    before_seq: z.coerce.number().int().min(1).optional(),
    after_seq: z.coerce.number().int().min(0).optional(),
    limit: z.coerce.number().int().min(1).max(100).default(50),
  })
  .refine((query) => query.before_seq === undefined || query.after_seq === undefined, {
    message: 'Use before_seq or after_seq, not both',
  });

export const PresenceQuery = z.object({
  user_ids: z
    .string()
    .transform((value) =>
      value
        .split(',')
        .map((id) => id.trim())
        .filter(Boolean),
    )
    .pipe(z.array(z.uuid()).min(1).max(100)),
});

// ─── Requests ──────────────────────────────────────────────────────────────

export const CreateConversationBody = z
  .discriminatedUnion('type', [
    z.object({ type: z.literal('DIRECT'), user_id: z.uuid() }),
    z.object({
      type: z.literal('GROUP'),
      name: Name,
      member_ids: z.array(z.uuid()).min(1).max(100),
    }),
    z.object({ type: z.literal('CHANNEL'), name: Name, description: Description.optional() }),
  ])
  .openapi('CreateConversationRequest');

export const UpdateConversationBody = z
  .object({
    name: Name.optional(),
    description: Description.optional(),
    archived: z.boolean().optional(),
  })
  .refine((body) => Object.values(body).some((value) => value !== undefined), {
    message: 'Provide at least one field to update',
  })
  .openapi('UpdateConversationRequest');

export const AddMembersBody = z
  .object({ user_ids: z.array(z.uuid()).min(1).max(100) })
  .openapi('AddConversationMembersRequest');

export const SendMessageBody = z
  .object({
    content: z.string().trim().max(4000).default('').openapi({
      description: 'May be empty when the message carries attachments',
      example: 'Chào cả nhà!',
    }),
    client_message_id: z
      .string()
      .regex(
        /^[A-Za-z0-9_-]{8,64}$/,
        'client_message_id must be 8-64 letters, digits, "-" or "_" (a UUID works)',
      )
      .openapi({
        description:
          'Generated by the client once per message and reused on retries, so a retry never ' +
          'creates a duplicate.',
        example: '0f8fad5b-d9cb-469f-a165-70867728950e',
      }),
    reply_to_id: z.uuid().optional(),
    attachment_ids: AttachmentIds.default([]),
  })
  .refine((body) => body.content.length > 0 || body.attachment_ids.length > 0, {
    message: 'Provide content or attachment_ids',
    path: ['content'],
  })
  .openapi('SendMessageRequest');

export const EditMessageBody = z.object({ content: MessageContent }).openapi('EditMessageRequest');

export const MarkReadBody = z.object({ seq: z.number().int().min(0) }).openapi('MarkReadRequest');

// ─── Responses ─────────────────────────────────────────────────────────────

export const MessageResponse = z
  .object({
    id: z.uuid(),
    conversation_id: z.uuid(),
    seq: z.number().int().openapi({ description: 'Server-assigned, gap-free order' }),
    sender: UserReference.nullable(),
    type: z.enum(['TEXT', 'IMAGE', 'FILE', 'SYSTEM']),
    content: z.string().nullable().openapi({ description: 'null once the message is deleted' }),
    attachments: z
      .array(AttachmentResponse)
      .openapi({ description: 'Empty once the message is deleted' }),
    reply_to_id: z.uuid().nullable(),
    client_message_id: z.string().nullable(),
    created_at: z.iso.datetime(),
    edited_at: z.iso.datetime().nullable(),
    deleted: z.boolean(),
  })
  .openapi('Message');

const ConversationBase = z.object({
  id: z.uuid(),
  type: ConversationTypeEnum,
  name: z.string().nullable(),
  description: z.string().nullable(),
  avatar_url: z.string().nullable(),
  slug: z.string().nullable(),
  archived: z.boolean(),
  last_message_seq: z.number().int(),
  last_message_at: z.iso.datetime().nullable(),
  created_at: z.iso.datetime(),
  member_count: z.number().int(),
  direct_peer: UserReference.nullable(),
});

export const ConversationSummaryResponse = ConversationBase.extend({
  my_role: ConversationRoleEnum,
  last_read_seq: z.number().int(),
  unread_count: z.number().int(),
  muted_until: z.iso.datetime().nullable(),
  last_message: MessageResponse.nullable(),
}).openapi('ConversationSummary');

export const ConversationDetailsResponse = ConversationBase.extend({
  my_role: ConversationRoleEnum.nullable(),
  last_read_seq: z.number().int().nullable(),
  unread_count: z.number().int().nullable(),
  members: z.array(
    z.object({
      user: UserReference.nullable(),
      role: ConversationRoleEnum,
      last_read_seq: z.number().int(),
      joined_at: z.iso.datetime(),
    }),
  ),
}).openapi('Conversation');

export const ChannelResponse = ConversationBase.omit({ direct_peer: true })
  .extend({ joined: z.boolean() })
  .openapi('Channel');

export type ConversationListQueryInput = z.infer<typeof ConversationListQuery>;
export type HistoryQueryInput = z.infer<typeof HistoryQuery>;
export type PresenceQueryInput = z.infer<typeof PresenceQuery>;
export type CreateConversationInput = z.infer<typeof CreateConversationBody>;
export type UpdateConversationInput = z.infer<typeof UpdateConversationBody>;
export type AddMembersInput = z.infer<typeof AddMembersBody>;
export type SendMessageInput = z.infer<typeof SendMessageBody>;
export type EditMessageInput = z.infer<typeof EditMessageBody>;
export type MarkReadInput = z.infer<typeof MarkReadBody>;
