/**
 * A curated set of emoji for the composer, not the whole Unicode table: these are the ones people
 * actually reach for at work, and keeping the list in the app means the picker needs no dependency
 * and matches the design system. Keywords are Vietnamese first, then English, so search works in
 * whichever language the person is typing.
 */
export interface EmojiGroup {
  /** Key under `chat.emoji.groups` in the dictionaries. */
  readonly id: string;
  readonly items: readonly (readonly [emoji: string, keywords: string])[];
}

export const EMOJI_GROUPS: readonly EmojiGroup[] = [
  {
    id: 'smileys',
    items: [
      ['😀', 'cười vui happy grin'],
      ['😃', 'cười vui happy smile'],
      ['😄', 'cười to happy laugh'],
      ['😁', 'cười tươi beam grin'],
      ['😆', 'cười lăn laugh haha'],
      ['😅', 'cười toát mồ hôi sweat laugh'],
      ['🤣', 'cười lăn lộn rofl'],
      ['😂', 'cười ra nước mắt joy tears'],
      ['🙂', 'mỉm cười slight smile'],
      ['😊', 'cười hiền blush happy'],
      ['😇', 'thiên thần angel innocent'],
      ['🙃', 'lộn ngược upside down'],
      ['😉', 'nháy mắt wink'],
      ['😍', 'mê tim heart eyes love'],
      ['🥰', 'yêu thương love smiling'],
      ['😘', 'hôn gió kiss'],
      ['😋', 'ngon yum tasty'],
      ['😎', 'ngầu cool sunglasses'],
      ['🤓', 'mọt sách nerd'],
      ['🤔', 'suy nghĩ thinking'],
      ['🤨', 'nghi ngờ raised eyebrow'],
      ['😐', 'mặt đơ neutral'],
      ['🙄', 'đảo mắt eye roll'],
      ['😏', 'nhếch mép smirk'],
      ['😴', 'buồn ngủ sleeping'],
      ['😪', 'mệt sleepy'],
      ['🥲', 'cười mà khóc tear smile'],
      ['😢', 'khóc cry sad'],
      ['😭', 'khóc to sobbing'],
      ['😤', 'hậm hực triumph huff'],
      ['😠', 'giận angry'],
      ['😡', 'tức giận rage'],
      ['🥵', 'nóng hot'],
      ['🥶', 'lạnh cold freezing'],
      ['😱', 'hoảng scream shock'],
      ['😳', 'ngượng flushed'],
      ['🤯', 'nổ não mind blown'],
      ['🤗', 'ôm hug'],
      ['🤫', 'suỵt shush quiet'],
      ['😬', 'ngại grimace awkward'],
      ['🥳', 'ăn mừng party celebrate'],
      ['🤒', 'ốm sick'],
      ['😷', 'khẩu trang mask'],
    ],
  },
  {
    id: 'gestures',
    items: [
      ['👍', 'like đồng ý thumbs up ok'],
      ['👎', 'không thích thumbs down'],
      ['👌', 'ok tốt perfect'],
      ['🤝', 'bắt tay handshake deal'],
      ['👏', 'vỗ tay clap bravo'],
      ['🙏', 'cảm ơn xin please thanks pray'],
      ['💪', 'cố lên mạnh strong muscle'],
      ['🤞', 'chúc may mắn fingers crossed'],
      ['✌️', 'yeah victory peace'],
      ['🤙', 'gọi call me'],
      ['👋', 'chào hello wave bye'],
      ['🖐️', 'bàn tay hand'],
      ['☝️', 'một điểm point up'],
      ['👇', 'bên dưới point down'],
      ['👉', 'bên phải point right'],
      ['👀', 'đang xem eyes looking'],
      ['🫡', 'tuân lệnh salute yes sir'],
      ['🫶', 'trái tim tay heart hands'],
      ['🤷', 'chịu shrug'],
      ['🤦', 'bó tay facepalm'],
      ['🙌', 'hoan hô raise hands'],
      ['✍️', 'ghi chép writing'],
    ],
  },
  {
    id: 'hearts',
    items: [
      ['❤️', 'tim đỏ red heart love'],
      ['🧡', 'tim cam orange heart'],
      ['💛', 'tim vàng yellow heart'],
      ['💚', 'tim xanh lá green heart'],
      ['💙', 'tim xanh dương blue heart'],
      ['💜', 'tim tím purple heart'],
      ['🖤', 'tim đen black heart'],
      ['🤍', 'tim trắng white heart'],
      ['💔', 'tan vỡ broken heart'],
      ['💕', 'hai tim two hearts'],
      ['💖', 'tim lấp lánh sparkling heart'],
      ['💯', 'một trăm điểm hundred perfect'],
      ['✨', 'lấp lánh sparkles'],
      ['⭐', 'sao star'],
      ['🌟', 'ngôi sao glowing star'],
      ['🔥', 'cháy hot fire'],
      ['🎉', 'chúc mừng party popper'],
      ['🎊', 'hoa giấy confetti'],
      ['🎁', 'quà gift present'],
      ['🏆', 'cúp trophy win'],
      ['🥇', 'huy chương vàng gold medal'],
      ['🎯', 'trúng đích target bullseye'],
    ],
  },
  {
    id: 'work',
    items: [
      ['✅', 'xong hoàn thành done check'],
      ['❌', 'sai huỷ cross no'],
      ['⚠️', 'cảnh báo warning'],
      ['❓', 'hỏi question'],
      ['❗', 'quan trọng exclamation'],
      ['📌', 'ghim pin'],
      ['📎', 'kẹp giấy paperclip attach'],
      ['📝', 'ghi chú note memo'],
      ['📅', 'lịch calendar'],
      ['⏰', 'báo thức alarm deadline'],
      ['⏳', 'chờ hourglass waiting'],
      ['📊', 'biểu đồ chart report'],
      ['📈', 'tăng chart up growth'],
      ['📉', 'giảm chart down'],
      ['💼', 'công việc briefcase work'],
      ['📁', 'thư mục folder'],
      ['📄', 'tài liệu document file'],
      ['🔗', 'liên kết link'],
      ['💡', 'ý tưởng idea bulb'],
      ['🚀', 'ra mắt launch rocket'],
      ['🐛', 'lỗi bug'],
      ['🔧', 'sửa fix wrench'],
      ['⚙️', 'cấu hình settings gear'],
      ['💻', 'máy tính laptop computer'],
      ['📱', 'điện thoại phone mobile'],
      ['✉️', 'thư email'],
      ['📞', 'gọi điện call phone'],
      ['🔔', 'thông báo bell notification'],
      ['🔍', 'tìm kiếm search'],
      ['🔒', 'khoá lock secure'],
    ],
  },
  {
    id: 'food',
    items: [
      ['☕', 'cà phê coffee'],
      ['🍵', 'trà tea'],
      ['🍺', 'bia beer'],
      ['🥤', 'nước ngọt drink'],
      ['🍰', 'bánh ngọt cake'],
      ['🎂', 'sinh nhật birthday cake'],
      ['🍕', 'pizza'],
      ['🍔', 'hamburger burger'],
      ['🍜', 'mì phở noodles'],
      ['🍚', 'cơm rice'],
      ['🍲', 'lẩu hotpot stew'],
      ['🥗', 'salad rau'],
      ['🍎', 'táo apple'],
      ['🍌', 'chuối banana'],
      ['🍉', 'dưa hấu watermelon'],
      ['🍫', 'sô cô la chocolate'],
      ['🍦', 'kem ice cream'],
      ['🧋', 'trà sữa bubble tea'],
    ],
  },
  {
    id: 'nature',
    items: [
      ['🐶', 'chó dog'],
      ['🐱', 'mèo cat'],
      ['🐼', 'gấu trúc panda'],
      ['🐷', 'lợn pig'],
      ['🐔', 'gà chicken'],
      ['🦄', 'kỳ lân unicorn'],
      ['🐝', 'ong bee'],
      ['🌸', 'hoa anh đào blossom flower'],
      ['🌺', 'hoa dâm bụt hibiscus'],
      ['🌻', 'hướng dương sunflower'],
      ['🌳', 'cây tree'],
      ['🌈', 'cầu vồng rainbow'],
      ['☀️', 'nắng sun sunny'],
      ['🌙', 'trăng moon night'],
      ['☁️', 'mây cloud'],
      ['🌧️', 'mưa rain'],
      ['❄️', 'tuyết snow cold'],
      ['🌊', 'sóng biển wave sea'],
    ],
  },
  {
    id: 'activity',
    items: [
      ['⚽', 'bóng đá football soccer'],
      ['🏀', 'bóng rổ basketball'],
      ['🏸', 'cầu lông badminton'],
      ['🎾', 'tennis'],
      ['🏃', 'chạy running'],
      ['🚴', 'đạp xe cycling'],
      ['🏊', 'bơi swimming'],
      ['🧘', 'thiền yoga meditation'],
      ['🎮', 'chơi game gaming'],
      ['🎵', 'nhạc music'],
      ['🎤', 'hát karaoke mic'],
      ['🎬', 'phim movie film'],
      ['📷', 'chụp ảnh camera photo'],
      ['✈️', 'máy bay travel plane'],
      ['🏖️', 'biển nghỉ mát beach holiday'],
      ['🏠', 'nhà home house'],
      ['🏢', 'văn phòng office building'],
      ['🚗', 'ô tô car'],
    ],
  },
];

/** Every emoji in one list, for search. */
export const ALL_EMOJI = EMOJI_GROUPS.flatMap((group) => group.items);
